language: java
install: true

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      script:
        - sh gradlew check
        - sh gradlew jacocoTestReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      if: tag IS present
      script:
        - sh gradlew bintrayUpload